version: '3.7'
services:
  postgres:
    container_name: postgresql
    image: postgres:10.5
    restart: always
    environment: 
      - POSTGRES_USER=baeldung
      - POSTGRES_PASSWORD=baeldung
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      # copy the sql script to fill tables
      - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
  pg_admin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    ports:
      - "5051:80"
    environment:
      - GUNICORN_THREADS=1
      - PGADMIN_DEFAULT_EMAIL=erx@email.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    depends_on:
      - postgres